@baseUrl = https://localhost:5000

### 🧬🔴 [DONOR] - Criar novo doador
POST {{baseUrl}}/api/donor
Content-Type: application/json

{
  "fullName": "João da Silva",
  "email": "joao@email.com",
  "birthDate": "1990-05-01",
  "genre": "M",
  "weight": 75.5,
  "rhFactor": "+",
  "bloodType": "O",
  "cep": "01001000"
}

### 🧬🟠 [DONOR] - Atualizar doador
PUT {{baseUrl}}/api/donor/1
Content-Type: application/json

{
  "idDonor": 1,
  "fullName": "João Atualizado",
  "email": "joao.novo@email.com",
  "genre": "M",
  "weight": 78.0,
  "bloodType": "O"
}

### 🧬⚫ [DONOR] - Deletar doador
DELETE {{baseUrl}}/api/donor/1

### 🧬🟢 [DONOR] - Buscar todos os doadores
GET {{baseUrl}}/api/donor

### 🧬🟢 [DONOR] - Buscar doador por ID
GET {{baseUrl}}/api/donor/1


### 💉🔴 [DONATION] - Criar nova doação
POST {{baseUrl}}/api/donation
Content-Type: application/json

{
  "quantityMl": 450,
  "idDonor": 1
}

### 💉⚫ [DONATION] - Deletar doação
DELETE {{baseUrl}}/api/donation/1

### 💉🟢 [DONATION] - Listar todas as doações
GET {{baseUrl}}/api/donation


### 🩸🔴 [BLOOD STOCK] - Criar novo estoque de sangue
POST {{baseUrl}}/api/bloodStock
Content-Type: application/json

{
  "bloodType": "A",
  "rhFactor": "+"
}

### 🩸🟠 [BLOOD STOCK] - Atualizar estoque
PUT {{baseUrl}}/api/bloodStock/1
Content-Type: application/json

{
  "idBloodStock": 1,
  "bloodType": "A",
  "quantityML": 500
}

### 🩸⚫ [BLOOD STOCK] - Deletar estoque
DELETE {{baseUrl}}/api/bloodStock/1

### 🩸🟢 [BLOOD STOCK] - Obter estoque por ID
GET {{baseUrl}}/api/bloodStock/1


### 🗺️🟢 [ADDRESS] - Obter endereço por CEP
GET {{baseUrl}}/api/address/cep/01001000

### 🗺️🟢 [ADDRESS] - Obter endereço por ID
GET {{baseUrl}}/api/address/id/1

### 🗺️🟢 [ADDRESS] - Obter todos os endereços
GET {{baseUrl}}/api/address
